export function getLeaderBoardSearch() {
	return {
		classes: [
			{
				id: 0,
				value: 'death Knight',
				img: '/images/deathknight.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 1,
				value: 'Demon Hunter',
				img: '/images/demonhunter.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 2,
				value: 'Druid',
				img: '/images/druid.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 3,
				value: 'Hunter',
				img: '/images/hunter.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 4,
				value: 'Mage',
				img: '/images/mage.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 5,
				value: 'monk',
				img: '/images/monk.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 6,
				value: 'Paladin',
				img: '/images/paladin.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 7,
				value: 'Priest',
				img: '/images/priest.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 8,
				value: 'Rogue',
				img: '/images/rogue.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 9,
				value: 'Shaman',
				img: '/images/shaman.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 10,
				value: 'Warlock',
				img: '/images/warlock.jpg',
				size: '24x24',
				isChecked: true,
			},
			{
				id: 11,
				value: 'warrior',
				img: '/images/warrior.jpg',
				size: '24x24',
				isChecked: true,
			},
		],
		regions: [
			{
				id: 0,
				value: 'US',
				img: '/images/region_us.png',
				size: '24x20',
				isChecked: true,
			},
			{
				id: 1,
				value: 'EU',
				img: '/images/region_eu.png',
				size: '24x20',
				isChecked: true,
			},
		],
		realms: [],
		rating: 0,
	};
}
